name: Build and Release APK

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0.x'

      # https://blog.taranissoftware.com/build-net-maui-apps-with-github-actions
      - name: Install MAUI Workload
        run: dotnet workload install maui --ignore-failed-sources
        
      - name: Restore NuGet Packages
        run: dotnet restore

      # https://stackoverflow.com/questions/74242135/net-maui-set-version-in-azure-pipelines
      - name: Build APK
        env:
            CSPROJ_FILE: YeetMacro2/YeetMacro2.csproj
            NEW_VERSION: ${{ github.run_number }}
        run: |
          echo 'Target Version: ${{ env.NEW_VERSION }}'
          dotnet build -f net7.0-android -c Release /p:ApplicationDisplayVersion=${{ env.NEW_VERSION }} /p:ApplicationVersion=${{ env.NEW_VERSION }}

     #- name: Upload APK as Release Asset
     #  uses: actions/upload-artifact@v1
     #  with:
     #    name: app-release
     #    path: YeetMacro2/bin/Release/net7.0-android/com.companyname.yeetmacro2-Signed.apk
      
      # https://github.com/softprops/action-gh-release
      - name: Attach Asset to Release
        uses: softprops/action-gh-release@v1
        with:
          body: Version ${{ github.run_number }}
          tag_name: "latest"
          files: YeetMacro2/bin/Release/net7.0-android/com.companyname.yeetmacro2-Signed.apk