name: Build and Release APK

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0.x'

      - name: Restore NuGet Packages
        run: dotnet restore

      - name: Build APK
        run: dotnet build -f net7.0-android -c Release

      - name: Upload APK as Release Asset
        uses: actions/upload-artifact@v2
        with:
          name: app-release
          path: YeetMacro2/bin/Release/net7.0/android/bin/*.apk